'use client'

import { useState } from 'react'
import { FaChartLine, FaTicketAlt, FaTable, FaFileExport } from 'react-icons/fa'
import Link from 'next/link'

interface NavItem {
  title: string
  href: string
  icon: React.ReactNode
}

export default function FinanceOfficerLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [currentSection, setCurrentSection] = useState('overview')

  const navigationItems: NavItem[] = [
    {
      title: 'Ticket Sales Overview',
      href: '/dashboard/finance-officer',
      icon: <FaTicketAlt />
    },
    {
      title: 'Match-wise Breakdown',
      href: '/dashboard/finance-officer/matches',
      icon: <FaTable />
    },
    {
      title: 'Analytics',
      href: '/dashboard/finance-officer/analytics',
      icon: <FaChartLine />
    },
    {
      title: 'Reports & Export',
      href: '/dashboard/finance-officer/reports',
      icon: <FaFileExport />
    }
  ]

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Header */}
      <header className="bg-white shadow-sm">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-gray-900">
              Finance Officer Dashboard – NCSM
            </h1>
            <div className="flex items-center space-x-4">
              <span className="text-sm text-gray-500">Last updated: {new Date().toLocaleString()}</span>
            </div>
          </div>
        </div>
      </header>

      {/* Navigation */}
      <nav className="bg-white shadow-sm mt-1">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex space-x-8 overflow-x-auto">
            {navigationItems.map((item) => (
              <Link
                key={item.href}
                href={item.href}
                className={`flex items-center px-3 py-4 text-sm font-medium border-b-2 ${
                  currentSection === item.href
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
                onClick={() => setCurrentSection(item.href)}
              >
                <span className="mr-2">{item.icon}</span>
                {item.title}
              </Link>
            ))}
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {children}
      </main>

      {/* Footer */}
      <footer className="bg-white shadow-sm mt-8">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4">
          <div className="text-center text-sm text-gray-500">
            Generated by NCSM Finance Dashboard
          </div>
        </div>
      </footer>
    </div>
  )
}
